# Generated by Django 6.0.6 on 2026-06-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(help_text="Date et heure fixées par l'administration")),
                ('type_rdv', models.CharField(choices=[('RETRAIT', 'Retrait de matériel'), ('RETOUR', 'Retour de matériel')], default='RETRAIT', max_length=10)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valider '), ('ANNULE', 'Annulé')], default='VALIDE', max_length=15)),
                ('administrateur', models.ForeignKey(blank=True, help_text="L'administrateur qui a fixé ce créneau", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous_administres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
