# Generated by Django 6.0.6 on 2026-06-21 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rendezvous', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='administrateur',
            field=models.ForeignKey(blank=True, help_text="L'administrateur qui a fixé ce créneau", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous_administres', to=settings.AUTH_USER_MODEL),
        ),
    ]
