# Generated by Django 6.0.6 on 2026-06-27 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0003_initial'),
        ('rendezvous', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date_heure'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='beneficiaire',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur convoqué", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_rendezvous', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='emprunt',
            field=models.ForeignKey(blank=True, help_text="La demande d'emprunt liée à ce rendez-vous", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='emprunts.emprunt'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=15),
        ),
    ]
