# Generated by Django 6.0.6 on 2026-07-02 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0003_alter_rendezvous_options_rendezvous_beneficiaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(default='Magasin Central UFR/SEA', max_length=200)),
                ('capacite', models.PositiveIntegerField(default=1, help_text='Nombre de RDV max sur ce créneau')),
            ],
            options={
                'verbose_name': 'Créneau de disponibilité',
                'verbose_name_plural': 'Créneaux de disponibilité',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='lieu',
            field=models.CharField(default='Magasin Central UFR/SEA', max_length=200),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='administrateur',
            field=models.ForeignKey(blank=True, help_text="L'administrateur qui a validé la demande", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous_administres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_heure',
            field=models.DateTimeField(help_text='Date et heure attribuées automatiquement'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='disponibilite',
            field=models.ForeignKey(blank=True, help_text='Le créneau hebdomadaire sur lequel ce RDV a été attribué', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='rendezvous.disponibilite'),
        ),
    ]
