# Generated by Django 6.0.6 on 2026-07-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('SIGNALE', 'Signalé')], default='ACTIF', help_text="Utilisé pour la suspension ou le signalement d'un compte.", max_length=10),
        ),
    ]
