# Generated by Django 6.0.6 on 2026-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('typeNotification', models.CharField(choices=[('INFO', 'Information'), ('ALERTE', 'Alerte / Panne'), ('EMPRUNT', 'Emprunt / Retour')], default='INFO', max_length=20)),
                ('dateNotification', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dateNotification'],
            },
        ),
    ]
