<<<<<<< HEAD
=======
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

>>>>>>> frontend-web
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*eto@2(9u=dgs%1=5@+d7+vkik#49(_7!_mmp4-wk853o55d=n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Autorise toutes les connexions (pratique pour tester avec le mobile)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
<<<<<<< HEAD
    
    # --- LES EXTENSIONS TIERS À RAJOUTER ICI ---
    'rest_framework',
    'rest_framework_simplejwt',
    
    # Les applications métiers créées
=======
    # Les applications métiers que j'ai créées @Jean Baptiste
    
    
    'rest_framework',
>>>>>>> origin/Ma-Partie-De-Gestion
=======
    
    # 🔌 Packages tiers indispensables pour l'API et la sécurité Web
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',  # Indispensable pour gérer le système de tokens JWT

    # Les applications métiers créées
>>>>>>> frontend-web
    'materiels',
    'utilisateurs',
    'emprunts',
    'maintenance',
    'notifications',
    'rendezvous',
    'historiques',
<<<<<<< HEAD
=======
    #API Documentation
>>>>>>> frontend-web
    'drf_spectacular',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 🌐 Intercepte les requêtes CORS en priorité
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

<<<<<<< HEAD
LANGUAGE_CODE = 'fr-fr'
=======
LANGUAGE_CODE = 'fr-fr'  # Configuration en français pour ton projet de stage
>>>>>>> frontend-web

TIME_ZONE = 'Africa/Ouagadougou'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
<<<<<<< HEAD
AUTH_USER_MODEL = 'utilisateurs.Utilisateur'

# Configuration de l'API REST avec JWT (JSON Web Tokens) pour l'authentification
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
=======

#  Configuration globale de Django REST Framework
REST_FRAMEWORK = {
    # Déclare le générateur de schéma OpenAPI (Swagger)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Déclare la méthode d'authentification par défaut de votre API
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

#  Configuration de drf-spectacular (Swagger UI)
SPECTACULAR_SETTINGS = {
    'TITLE': 'API Gestion-Matériel',
    'DESCRIPTION': 'Documentation interactive des API du système de gestion et traçabilité des matériels pédagogiques.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # Intégration propre du bouton "Authorize" (Cadenas) dans Swagger pour le token JWT
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{
        'jwtAuth': [],
    }],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'jwtAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'Entrez votre token JWT sous la forme : Bearer <votre_token_ici>'
            }
        }
    }
}

#  Autorisation des requêtes cross-origin en développement (React/Flutter)
CORS_ALLOW_ALL_ORIGINS = True
>>>>>>> frontend-web
