# Generated by Django 6.0.6 on 2026-06-16 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateTimeField(verbose_name='Date de retour prévue')),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour réelle')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu / Dégradé')], default='EN_COURS', max_length=20)),
                ('observations', models.TextField(blank=True, help_text="Notes sur l'état du matériel", null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_sortie'],
            },
        ),
    ]
