# Generated by Django 6.0.6 on 2026-06-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0001_initial'),
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historique_emprunts', to='materiels.materiel', verbose_name='Matériel emprunté'),
        ),
    ]
