# Generated by Django 6.0.6 on 2026-06-21 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprunts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur'),
        ),
    ]
