# Generated by Django 6.0.6 on 2026-06-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu / Dégradé'), ('REFUSE', 'Refusé')], default='EN_COURS', max_length=20),
        ),
    ]
