# Generated by Django 6.0.6 on 2026-07-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0005_alter_emprunt_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='date_retour_declare',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de déclaration du retour'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='etat_retour',
            field=models.CharField(blank=True, choices=[('BON_ETAT', 'Bon état'), ('ENDOMMAGE', 'Endommagé'), ('HORS_SERVICE', 'Hors service'), ('INCOMPLET', 'Incomplet')], max_length=20, null=True, verbose_name='État du matériel au retour'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('EN_COURS', 'En cours'), ('RETOUR_DECLARE', 'Retour déclaré'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu / Dégradé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
