# Generated by Django 6.0.6 on 2026-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('EMPRUNT', 'Emprunt'), ('RETOUR', 'Retour'), ('MAINTENANCE', 'Maintenance'), ('RENDEZVOUS', 'Rendez-vous'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet')], max_length=20)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
