# Generated by Django 6.0.6 on 2026-07-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='role_utilisateur',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
