# Generated by Django 6.0.6 on 2026-06-21 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='materiels.materiel'),
        ),
    ]
