# Generated by Django 6.0.6 on 2026-07-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='technicien',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
