# Generated by Django 6.0.6 on 2026-06-16 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('localisation', models.CharField(max_length=150)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disopnible'), ('INDISPONIBLE', 'Indisponible'), ('EMPRUNTE', 'Emprunté')], default='Disponible', max_length=20)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('quantite_disponible', models.PositiveIntegerField(default=1)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='materiels/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiels', to='materiels.categorie')),
            ],
        ),
    ]
