# Generated by Django 6.0.6 on 2026-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Nom du matériel')),
                ('code_barre', models.CharField(max_length=100, unique=True, verbose_name="Code barre / Numéro d'inventaire")),
                ('categorie', models.CharField(choices=[('ORDINATEUR', 'Ordinateur'), ('PROJECTEUR', 'Vidéoprojecteur'), ('RESEAU', 'Équipement Réseau (Routeur, Switch)'), ('ACCESSOIRE', 'Accessoire (Câble, Adaptateur, Souris)')], default='ORDINATEUR', max_length=50)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EMPRUNTE', 'Emprunté'), ('EN_PANNE', 'En panne / Maintenance'), ('REFORME', 'Mis au rebut / Archivé')], default='DISPONIBLE', max_length=20)),
                ('caracteristiques', models.TextField(blank=True, help_text='Spécifications techniques (RAM, Stockage, etc.)', null=True)),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name="Date d'achat / acquisition")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['designation'],
            },
        ),
    ]
