# Generated by Django 6.0.6 on 2026-06-21 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, verbose_name='Nom du matériel')),
                ('code_barre', models.CharField(max_length=100, unique=True, verbose_name="Code barre / Numéro d'inventaire")),
                ('libelle', models.CharField(blank=True, max_length=150, null=True)),
                ('categorie_type', models.CharField(choices=[('ORDINATEUR', 'Ordinateur'), ('PROJECTEUR', 'Vidéoprojecteur'), ('RESEAU', 'Équipement Réseau (Routeur, Switch)'), ('ACCESSOIRE', 'Accessoire (Câble, Adaptateur, Souris)'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EMPRUNTE', 'Emprunté'), ('EN_PANNE', 'En panne / Maintenance'), ('REFORME', 'Mis au rebut / Archivé')], default='DISPONIBLE', max_length=20)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible'), ('EMPRUNTE', 'Emprunté'), ('EN_MAINTENANCE', 'En maintenance')], default='DISPONIBLE', max_length=20)),
                ('emplacement_physique', models.CharField(default='Dépôt Central', max_length=150)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('quantite_disponible', models.PositiveIntegerField(default=1)),
                ('caracteristiques', models.TextField(blank=True, help_text='Spécifications techniques (RAM, Stockage, etc.)', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='materiels/')),
                ('date_acquisition', models.DateField(blank=True, null=True, verbose_name="Date d'achat / acquisition")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materiels', to='materiels.categorie')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['designation'],
            },
        ),
    ]
