# Generated by Django 6.0.6 on 2026-06-17 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='localisation',
        ),
        migrations.AddField(
            model_name='materiel',
            name='detenteur_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_empruntes', to=settings.AUTH_USER_MODEL, verbose_name='Détenu par'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='emplacement_physique',
            field=models.CharField(default='Dépôt Central', max_length=150),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('DISPONIBLE', 'Disopnible'), ('INDISPONIBLE', 'Indisponible'), ('EMPRUNTE', 'Emprunté'), ('EnMaintenance', 'En maintenance')], default='DISPONIBLE', max_length=20),
        ),
    ]
