# Generated by Django 6.0.6 on 2026-07-08 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du kit')),
                ('code_kit', models.CharField(max_length=100, unique=True, verbose_name='Code du kit')),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kits/')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EMPRUNTE', 'Emprunté'), ('INCOMPLET', 'Incomplet (un exemplaire manquant/en panne)')], default='DISPONIBLE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kit de matériel',
                'verbose_name_plural': 'Kits de matériel',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(help_text='Ex: MAT-2026-00123', max_length=100, unique=True, verbose_name='Numéro de série / Code unique')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EMPRUNTE', 'Emprunté'), ('EN_PANNE', 'En panne / Maintenance'), ('REFORME', 'Mis au rebut / Archivé')], default='DISPONIBLE', max_length=20)),
                ('emplacement_physique', models.CharField(blank=True, max_length=150, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('detenteur_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemplaires_empruntes', to=settings.AUTH_USER_MODEL, verbose_name='Détenu par')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='materiels.materiel', verbose_name='Modèle de matériel')),
            ],
            options={
                'verbose_name': 'Exemplaire',
                'verbose_name_plural': 'Exemplaires',
                'ordering': ['materiel', 'numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='KitExemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.exemplaire')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.kit')),
            ],
            options={
                'verbose_name': 'Composition du kit',
                'verbose_name_plural': 'Compositions du kit',
                'unique_together': {('kit', 'exemplaire')},
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='exemplaires',
            field=models.ManyToManyField(blank=True, related_name='kits', through='materiels.KitExemplaire', to='materiels.exemplaire'),
        ),
    ]
